"""empty message

Revision ID: 2479f8f04725
Revises: bba95fc0874f
Create Date: 2017-04-07 03:47:37.902594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2479f8f04725'
down_revision = 'bba95fc0874f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_attributes', sa.Column('comments', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_attributes', 'comments')
    # ### end Alembic commands ###
