"""empty message

Revision ID: bba95fc0874f
Revises: f337393e41b0
Create Date: 2017-04-07 03:44:41.561322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bba95fc0874f'
down_revision = 'f337393e41b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute_types', 'last_update')
    op.drop_column('attributes', 'last_update')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('last_update', mysql.DATETIME(), nullable=True))
    op.add_column('attribute_types', sa.Column('last_update', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
