"""empty message

Revision ID: f337393e41b0
Revises: 635e56ab6fdb
Create Date: 2017-04-07 03:40:59.646386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f337393e41b0'
down_revision = '635e56ab6fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_attributes', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.add_column('character_attributes', sa.Column('value', sa.Integer(), nullable=True))
    op.add_column('experience_logs', sa.Column('character_id', sa.Integer(), nullable=True))
    op.drop_constraint('experience_logs_ibfk_1', 'experience_logs', type_='foreignkey')
    op.create_foreign_key(None, 'experience_logs', 'characters', ['character_id'], ['id'])
    op.drop_column('experience_logs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience_logs', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'experience_logs', type_='foreignkey')
    op.create_foreign_key('experience_logs_ibfk_1', 'experience_logs', 'users', ['user_id'], ['id'])
    op.drop_column('experience_logs', 'character_id')
    op.drop_column('character_attributes', 'value')
    op.drop_column('character_attributes', 'last_modified')
    # ### end Alembic commands ###
